config/routes.rb
Rails.application.routes.draw do
  
    resources :concessionaria
    resources :carros
    resources :clientes

    root to:"page#index"
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/carro.rb
class Carro < ApplicationRecord
    belongs_to :cliente
end

app/models/cliente.rb
class Cliente < ApplicationRecord
has_many :carros
end

app/models/concessionarium.rb
class Concessionarium < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carros_controller.rb
class CarrosController < ApplicationController
  before_action :set_carro, only: %i[ show edit update destroy ]

  # GET /carros or /carros.json
  def index
    @carros = Carro.all
  end

  # GET /carros/1 or /carros/1.json
  def show
  end

  # GET /carros/new
  def new
    @carro = Carro.new
  end

  # GET /carros/1/edit
  def edit
  end

  # POST /carros or /carros.json
  def create
    @carro = Carro.new(carro_params)

    respond_to do |format|
      if @carro.save
        format.html { redirect_to @carro, notice: "Carro was successfully created." }
        format.json { render :show, status: :created, location: @carro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @carro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carros/1 or /carros/1.json
  def update
    respond_to do |format|
      if @carro.update(carro_params)
        format.html { redirect_to @carro, notice: "Carro was successfully updated." }
        format.json { render :show, status: :ok, location: @carro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @carro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carros/1 or /carros/1.json
  def destroy
    @carro.destroy
    respond_to do |format|
      format.html { redirect_to carros_url, notice: "Carro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carro
      @carro = Carro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def carro_params
      params.require(:carro).permit(:placa, :modelo, :chassi, :ano, :cliente_id)
    end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: %i[ show edit update destroy ]

  # GET /clientes or /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1 or /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes or /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: "Cliente was successfully created." }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1 or /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: "Cliente was successfully updated." }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1 or /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: "Cliente was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cliente_params
      params.require(:cliente).permit(:documento, :nome, :email, :telefone)
    end
end

app/controllers/concessionaria_controller.rb
class ConcessionariaController < ApplicationController
  before_action :set_concessionarium, only: %i[ show edit update destroy ]

  # GET /concessionaria or /concessionaria.json
  def index
    @concessionaria = Concessionarium.all
  end

  # GET /concessionaria/1 or /concessionaria/1.json
  def show
  end

  # GET /concessionaria/new
  def new
    @concessionarium = Concessionarium.new
  end

  # GET /concessionaria/1/edit
  def edit
  end

  # POST /concessionaria or /concessionaria.json
  def create
    @concessionarium = Concessionarium.new(concessionarium_params)

    respond_to do |format|
      if @concessionarium.save
        format.html { redirect_to @concessionarium, notice: "Concessionarium was successfully created." }
        format.json { render :show, status: :created, location: @concessionarium }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @concessionarium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concessionaria/1 or /concessionaria/1.json
  def update
    respond_to do |format|
      if @concessionarium.update(concessionarium_params)
        format.html { redirect_to @concessionarium, notice: "Concessionarium was successfully updated." }
        format.json { render :show, status: :ok, location: @concessionarium }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @concessionarium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concessionaria/1 or /concessionaria/1.json
  def destroy
    @concessionarium.destroy
    respond_to do |format|
      format.html { redirect_to concessionaria_url, notice: "Concessionarium was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concessionarium
      @concessionarium = Concessionarium.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def concessionarium_params
      params.require(:concessionarium).permit(:nome, :cidade, :endereço, :anos_de_mercado)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carros_helper.rb
module CarrosHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/concessionaria_helper.rb
module ConcessionariaHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/carros/_form.html.erb
<%= form_with(model: carro) do |form| %>
  <% if carro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(carro.errors.count, "error") %> prohibited this carro from being saved:</h2>

      <ul>
        <% carro.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :placa %>
    <%= form.text_field :placa %>
  </div>

  <div class="field">
    <%= form.label :modelo %>
    <%= form.text_field :modelo %>
  </div>

  <div class="field">
    <%= form.label :chassi %>
    <%= form.text_field :chassi %>
  </div>

  <div class="field">
    <%= form.label :ano %>
    <%= form.number_field :ano %>
  </div>

  <div class="field">
    <%= form.label :cliente %>
    <%= form.select :cliente_id, Cliente.all.map{ |x| [x.nome, x.id]} %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>



<% end %>

app/views/carros/edit.html.erb
<h1>Editing Carro</h1>

<%= render 'form', carro: @carro %>

<%= link_to 'Show', @carro %> |
<%= link_to 'Back', carros_path %>

app/views/carros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carros</h1>

<table>
  <thead>
    <tr>
      <th>Placa</th>
      <th>Modelo</th>
      <th>Chassi</th>
      <th>Ano</th>
        <th>Cliente</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carros.each do |carro| %>
      <tr>
        <td><%= carro.placa %></td>
        <td><%= carro.modelo %></td>
        <td><%= carro.chassi %></td>
        <td><%= carro.ano %></td>
        <td><%= carro.try(:cliente).try(:nome) %></td>
        <td><%= link_to 'Detalhes', carro, class: "bt-info bt" %></td>
        <td><%= link_to 'Editar', edit_carro_path(carro), class: "bt-blue bt" %></td>
        <td><%= link_to 'Remover', carro, method: :delete, data: { confirm: 'Are you sure?' }, class: "bt-danger bt" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo carro', new_carro_path, class: "bt-green bt" %>

app/views/carros/new.html.erb
<h1>New Carro</h1>

<%= render 'form', carro: @carro %>

<%= link_to 'Back', carros_path %>

app/views/carros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Placa:</strong>
  <%= @carro.placa %>
</p>

<p>
  <strong>Modelo:</strong>
  <%= @carro.modelo %>
</p>

<p>
  <strong>Chassi:</strong>
  <%= @carro.chassi %>
</p>

<p>
  <strong>Ano:</strong>
  <%= @carro.ano %>
</p>

<%= link_to 'Edit', edit_carro_path(@carro) %> |
<%= link_to 'Back', carros_path %>

app/views/clientes/_form.html.erb
<%= form_with(model: cliente) do |form| %>
  <% if cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
        <% cliente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :documento %>
    <%= form.text_field :documento %>
  </div>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clientes</h1>

<table>
  <thead>
    <tr>
      <th>Documento</th>
      <th>Nome</th>
      <th>Email</th>
      <th>Telefone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.documento %></td>
        <td><%= cliente.nome %></td>
        <td><%= cliente.email %></td>
        <td><%= cliente.telefone %></td>
        <td><%= link_to 'Detalhes', cliente, class: "bt-info bt" %></td>
        <td><%= link_to 'Editar', edit_cliente_path(cliente), class: "bt-blue bt"  %></td>
        <td><%= link_to 'Remover', cliente, method: :delete, data: { confirm: 'Are you sure?' }, class: "bt-danger bt" %></td>
      </tr
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Cliente', new_cliente_path, class: "bt-green bt" %>

app/views/clientes/new.html.erb
<h1>New Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Documento:</strong>
  <%= @cliente.documento %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @cliente.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @cliente.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @cliente.telefone %>
</p>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>

app/views/concessionaria/_form.html.erb
<%= form_with(model: concessionarium) do |form| %>
  <% if concessionarium.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(concessionarium.errors.count, "error") %> prohibited this concessionarium from being saved:</h2>

      <ul>
        <% concessionarium.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :cidade %>
    <%= form.text_field :cidade %>
  </div>

  <div class="field">
    <%= form.label :endereço %>
    <%= form.text_field :endereço %>
  </div>

  <div class="field">
    <%= form.label :anos_de_mercado %>
    <%= form.text_field :anos_de_mercado %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/concessionaria/edit.html.erb
<h1>Editing Concessionarium</h1>

<%= render 'form', concessionarium: @concessionarium %>

<%= link_to 'Show', @concessionarium %> |
<%= link_to 'Back', concessionaria_path %>

app/views/concessionaria/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Concessionaria</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cidade</th>
      <th>Endereço</th>
      <th>Anos de mercado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concessionaria.each do |concessionarium| %>
      <tr>
        <td><%= concessionarium.nome %></td>
        <td><%= concessionarium.cidade %></td>
        <td><%= concessionarium.endereço %></td>
        <td><%= concessionarium.anos_de_mercado %></td>
        <td><%= link_to 'Detalhes', concessionarium, class:"bt-info bt" %></td>
        <td><%= link_to 'Editar', edit_concessionarium_path(concessionarium), class:"bt-blue bt" %></td>
        <td><%= link_to 'Remover', concessionarium, method: :delete, data: { confirm: 'Are you sure?' }, class: "bt-danger bt" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova concessionaria', new_concessionarium_path, class: "bt-green bt" %>

app/views/concessionaria/new.html.erb
<h1>New Concessionarium</h1>

<%= render 'form', concessionarium: @concessionarium %>

<%= link_to 'Back', concessionaria_path %>

app/views/concessionaria/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @concessionarium.nome %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @concessionarium.cidade %>
</p>

<p>
  <strong>Endereço:</strong>
  <%= @concessionarium.endereço %>
</p>

<p>
  <strong>Anos de mercado:</strong>
  <%= @concessionarium.anos_de_mercado %>
</p>

<%= link_to 'Edit', edit_concessionarium_path(@concessionarium) %> |
<%= link_to 'Back', concessionaria_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TemplateRubyOnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="navbar"> 
      <ul>
      <li>
      <a href="/">home</a>
      </li>
      <li>
      <a href="/carros">carros</a>
      </li>
      <li>
      <a href="/clientes">clientes</a>
      </li>
      <li>
      <a href="/concessionaria">concessionarias</a>
      </li>
      </ul>
    </div>
    <div id="content">
    <%= yield %>
    </div>
  </body>
</html>

app/views/page/index.html.erb
<h1>Armarinho Rochelle</h1>
<h2>As melhores linhas para voce</h2>